databases:
  - name: saboria-db
    plan: free

services:
  - type: web
    name: saboria
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MEALDB_API_KEY
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: saboria-db
          property: connectionString
